---

- name: copy elasticsearch exporter script
  template:
    src: "es_exporter"
    dest: /usr/local/bin/es_exporter
    mode: 0755
    owner: root
    group: root

- name: copy elasticsearch exporter script
  template:
    src: "es_exporter.service"
    dest: /etc/systemd/system/es_exporter.service
    mode: 0644
    owner: root
    group: root

- name: restart elasticsearch exporter service is restarted
  service:
    name: es_exporter
    state: restarted
  changed_when: false

- name: wait for elasticsearch exporter to become ready
  wait_for:
    host: "{{ es_exporter_server_bind }}"
    port: "{{ es_exporter_server_port }}"
    state: started
    delay: 5
    connect_timeout: 15
    timeout: 300